### ISSUE TITLE
Question: have you seen graphql-go/graphql?

### ISSUE THREAD

**Issue by gmlewis** [shurcooL/graphql#1]
Have you checked out [graphql-go/graphql](https://github.com/graphql-go/graphql)?
Is it possible to consolidate the two?
I ask here because the other one appears to be older.

**Comment by shurcooL** [comment]
I have seen it and researched it when opening https://github.com/google/go-github/issues/646. Unless I'm missing something, it has nothing in common with this repository, aside from being related to GraphQL protocol. That repo is a Go GraphQL **server** implementation. This one is a Go GraphQL **client** implementation.

Also, there are two well-known Go GraphQL server implementations:

- https://github.com/graphql-go/graphql
- https://github.com/neelance/graphql-go

As far as I know, the second is better (more actively maintained and developed, better API, better features, etc.). So my recommendation is to use `github.com/neelance/graphql-go` for GraphQL server needs, and `github.com/shurcooL/graphql` for GraphQL client needs.

Final point, this package is a general GraphQL client. It powers https://github.com/shurcooL/githubql, which is a package specific to GitHub GraphQL API v4.

**Comment by gmlewis** [comment]
Excellent... thank you, @shurcooL, for the explanation!
