### ISSUE TITLE
Include response body in 'unexpected status' error message.

### ISSUE THREAD

**Issue by cjwagner** [shurcooL/graphql#29]
The response body would be very useful for debugging error messages for unexpected statuses. Many 4xx and 5xx responses include useful explanations in their body text.
In particular the https://github.com/kubernetes/test-infra repo uses the https://github.com/shurcooL/githubv4 library to interact with GitHub's v4 API and we are seeing lots of 502 and 403 errors that should include explanations in the response bodies.
ref: https://github.com/kubernetes/test-infra/issues/7466

The error is generated here: https://github.com/shurcooL/graphql/blob/365899397c9ad12805631fe4c9b2a64be9d74818/graphql.go#L72-L74
Adding a best effort `ReadAll` of the response body and appending it to the error text would make this error message much more useful.

I'd be happy to PR this change if this seems reasonable.

**Comment by dmitshur** [comment]
Ok, I think adding a `ReadAll` on the response body and including it in the error text is a reasonable first step to make, for now. Let's do that.

> we are seeing lots of 502 and 403 errors that should include explanations in the response bodies.

I'm not sure whether to use %s or %q to format the response body. @cjwagner, would you be able to share sample response bodies during those errors, if you have them available?

A bigger step might be to create a struct error type with a `ResponseBody []byte` field in it, but I'd rather defer that until it's really needed.

I've sent PR #30, we can discuss the details there.

**Comment by cjwagner** [comment]
Here is an example: ```Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include 'EA06:8FDC:2D9BD3C:56E05DD:599AFE05' when reporting this issue.```

The solution shouldn't be specific to the format or contents of the response body though since this is just an example from GitHub. The `%q` format token is more appropriate than `%s` or `"%s"` here as it will clearly indicate the start and end of the contents by escaping any `"`s.
