### ISSUE TITLE
Support for Inline Fragments

### ISSUE THREAD

**Issue by artonge** [shurcooL/graphql#3]
Hi,

Any plan to support [Inline Fragments](http://graphql.org/learn/queries/#inline-fragments) ?

Example :
```graphql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {  # <-- Inline Fragments
      primaryFunction
    }
  }
}
```
Do you think it would be feasible ?

Edit: manage to do without it. But it would be a nice feature :)

**Comment by shurcooL** [comment]
Yes, inline fragments are supported well. I still need to work on adding a section to README that explains how to use them. Let's use this issue to track that.

In the meantime, see issue https://github.com/shurcooL/githubql/issues/10 which was about union + inline fragment support. It was resolved in https://github.com/shurcooL/githubql/pull/15.

> Edit: manage to do without it. But it would be a nice feature :)

Can you show you did it it? Then I can suggest a better way, if there is one.

**Comment by artonge** [comment]
> Can you show you did it it? Then I can suggest a better way, if there is one.

I just found a way that don't need inline fragment in the API I use.

**Comment by shurcooL** [comment]
I see. Here's how you can do the above GraphQL query using `graphql` syntax:

```GraphQL
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {  # Inline Fragment.
      primaryFunction
    }
  }
}
```

```Go
var query struct {
	Hero struct {
		Name  graphql.String
		Droid struct {
			PrimaryFunction graphql.String
		} `graphql:"... on Droid"` // Inline Fragment.
	} `graphql:"hero(episode: $ep)"`
}
```

**Comment by shurcooL** [comment]
@artonge, have you had a chance to try the above? Any issues?

**Comment by artonge** [comment]
Hi,
Sorry I was in holidays.
No I didn't tried it as I found an other way to do what I wanted.

**Comment by shurcooL** [comment]
The support for inline fragments is documented in README now:

[https://github.com/shurcooL/graphql#inline-fragments](https://github.com/shurcooL/graphql/tree/cf6db17b893acfad0ca1929ba6be45bf854790ed#inline-fragments)

/cc @artonge FYI.
