### ISSUE TITLE
Error while generating graphql query with variables

### ISSUE THREAD

**Issue by alexander-myltsev** [shurcooL/graphql#6]
The query and variables as follows:

```go
var query struct {
	NameStringsByUuid []struct {
		InputId graphql.String `graphql:"inputId"`
	} `graphql:"nameStringsByUuid(uuids:[$someid1, $someid2])"`
}

	variables := map[string]interface{}{
		"someid1": graphql.ID("7db4f8a2-aafe-56b6-8838-89522c67d9f0"),
		"someid2": graphql.ID("a5cd7171-03e3-5d36-88a4-8eb921f4d159"),
	}
```

Produces query with errors (no commas between query parameters):
 
```graphql
query($someid1:ID!$someid2:ID!){nameStringsByUuid(uuids:[$someid1, $someid2]){inputId}}
```

On the other hand, when I'm using queries as follows:

```go
var query struct {
	NameStringsByUuid []struct {
		InputId graphql.String `graphql:"inputId"`
	} `graphql:"nameStringsByUuid(uuids:[$someids])"`
}

	variables := map[string]interface{}{
		"someids": []graphql.ID{
			graphql.ID("7db4f8a2-aafe-56b6-8838-89522c67d9f0"),
			graphql.ID("a5cd7171-03e3-5d36-88a4-8eb921f4d159"),
		},
	}
```

It produces query with errors too (variable type should be `$someids:[ID!]!` with bang in the end):

```graphql
query($someids:[ID!]){nameStringsByUuid(uuids:[$someids]){inputId}}
```

Is it a bug, or am I doing something wrong?

**Comment by shurcooL** [comment]
Thanks for reporting this, I will investigate.

**Comment by shurcooL** [comment]
> Produces query with errors (no commas between query parameters):

This part might be intentional. My intention was to produce a minified query. When I tested against GitHub's GraphQL server, it accepted comma-less query parameters without issues.

See the following test-case:

https://github.com/shurcooL/graphql/blob/671b933639ae10534edc12900803e2c1d7dfb9b5/query_test.go#L163-L168

Can you tell me what you're basing the statement that omitting commas is an error? Is it because it looks wrong, or is it failing to work?

Of course, our best bet is to look into the GraphQL spec to see whether omitting commas is considered valid or not.

**Comment by shurcooL** [comment]
http://facebook.github.io/graphql/October2016/#sec-Insignificant-Commas and http://facebook.github.io/graphql/October2016/#sec-List-Value seem to suggest that omitting commas is indeed a valid thing to do:

> Similar to white space and line terminators, commas (,) are used to improve the legibility of source text and separate lexical tokens but are otherwise syntactically and semantically insignificant within GraphQL query documents.

> Commas are optional throughout GraphQL so trailing commas are allowed and repeated commas do not represent missing values.

**Comment by shurcooL** [comment]
> It produces query with errors too (variable type should be `$someids:[ID!]!` with bang in the end):
>
> ```graphql
> query($someids:[ID!]){nameStringsByUuid(uuids:[$someids]){inputId}}
> ```

That part seems to be a legitimate issue. Basically, I hadn't run into that situation yet, so the code that handles it was left incomplete.

**Comment by shurcooL** [comment]
@alexander-myltsev, please see PR #7, it resolves this issue.

**Comment by alexander-myltsev** [comment]
@shurcooL works for me now.

**Comment by shurcooL** [comment]
Thanks for testing, and for reporting this issue! I'll merge the PR now.
