### ISSUE TITLE
FaunaDB graphql _id defined as _ID not exported

### ISSUE THREAD

**Issue by endrureza** [shurcooL/graphql#89]
I defined a struct of post like below

```
type Post struct {
  _ID graphql.ID
  Title graphql.String
}
```

it gives me error message 

```
struct field for "_id" doesn't exist in any of 1 places to unmarshal
```

while it give me error message

```
Message: Cannot query field 'id' on type 'Post'. Did you mean '_id'? (line 1, column 47):
query ($postId:ID!){findPostByID(id: $postId){id,title}}}
```

if i define the struct field like 

```
type Post struct {
  ID graphql.ID
  Title graphql.String
}
```

I'm using FaunaDB graphql by the way, where their id reference is `_id`, is there any way to solve this one ?

**Comment by dmitshur** [comment]
This might be a bug in the automatic mapping between Go struct field names and GraphQL fields. If so, the fix will belong there.

Can you see if it's possible to work around it temporarily by setting the name explicitly via a string literal tag `graphql`, perhaps like so:

```Go
type Post struct {
	_ID graphql.ID `graphql:"_id"`
	// Or:
	// ID graphql.ID `graphql:"_id"`

	Title graphql.String
}
```

**Comment by endrureza** [comment]
> ```go
> _ID graphql.ID `graphql:"_id"`
> ```

```
ID graphql.ID `graphql:"_id"`
```

that one works. thanks @dmitshur

**Comment by dmitshur** [comment]
Ah, the underscore in `_ID` makes it an unexported field, which cannot be accessed via reflection:

https://go.dev/play/p/g3UVxxue_vy

So using `ID` (or any other exported name) as the Go field name and setting the graphql name explicitly is the only possible fix.
